const giaiPhauNguoi = [
    {
        id: 0,
        title: "Bài 1. Đại cương về hệ xương - khớp",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 1,
        title: "Bài 2. Đại cương về hệ cơ - cơ và mạc của đầu",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 2,
        title: "Bài 3. Cơ-mạc của cổ và thân",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 3,
        title: "Bài 4A. Thành ngực - bụng và ống bẹn",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 4,
        title: "Bài 4B. Đáy chậu",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 5,
        title: "Bài 5. Cơ cùa các vùng nách và cánh tay",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 6,
        title: "Bài 6. Cơ của các vùng cảng tay và bàn tay",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 7,
        title: "Bài 7. Cơ của các vùng mông và đùi",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 8,
        title: "Bài 8. Cơ của các vùng cẳng chân và bàn chân",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 9,
        title: "Bài 9. Động mạch dưới đòn và các động mạch cảnh",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 10,
        title: "Bài 10. Tĩnh mạch và thần kinh của đầu - cổ",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 11,
        title: "Bài 11. Mạch máu của các chi",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 12,
        title: "Bài 12. Thần kinh của chi trên",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 13,
        title: "Bài 13. Thần kinh của chi dưới",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 14,
        title: "Bài 14. Mắt và thần kinh thị giác",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 15,
        title: "Bài 15. Tai và thần kinh tiền đình-ốc tai",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 16,
        title: "Bài 16. Mũi và thần kinh khứu giác, hầu",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 17,
        title: "Bài 17. Thanh quản, khí quản và các tuyến có liên quan",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 18,
        title: "Bài 18. Phế quản chính, cuống phổi và phổi",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 19,
        title: "Bài 19. Đại cương hệ tuần hoàn, các mạch chủ, tĩnh mạch cửa, hệ tĩnh mạch đơn và tỳ",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 20,
        title: "Bài 20. Tim và hệ bạch huyết",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 21,
        title: "Bài 21. Miệng và thực quản",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 22,
        title: "Bài 22. Trung thất, ố bụng và phúc mạc",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 23,
        title: "Bài 23. Dạ dày, ruột non và tuỵ",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 24,
        title: "Bài 24. Gan, đường mật ngoài gan và cuống gan",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 25,
        title: "Bài 25. Ruột già",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 26,
        title: "Bài 26. Mạch và thần kinh của các cơ quan tiêu hoá trong bụng",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 27,
        title: "Bài 27. Thận và niệu quản",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 28,
        title: "Bài 28. Bàng quang, niệu đạo và hệ sinh dục nam",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 29,
        title: "Bài 29. Hệ sinh dục nữ",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 30,
        title: "Bài 30. Đại cương về hệ thần kinh. Các màng não - tuỷ",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 31,
        title: "Bài 31. Tuỷ sống",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 32,
        title: "Bài 32. Thân não và tiểu não",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 33,
        title: "Bài 33. Các thần kinh sọ",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 34,
        title: "Bài 34. Gian não. Các não thất IV và III",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 35,
        title: "Bài 35. Đại não",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 36,
        title: "Bài 36. Hệ thần kinh tự chủ",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 37,
        title: "Bài 37. Các đường dẫn truyền thần kinh",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 38,
        title: "Bài 38. Hệ nội tiết",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 39,
        title: "Bài 39. Các xương và khớp của đầu",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 40,
        title: "Bài 40. Các xương và khớp của thân",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 41,
        title: "Bài 41. Các xương và khớp của chi trên",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
    {
        id: 42,
        title: "Bài 42. Các xương và khớp của chi dưới",
        src: "https://drive.google.com/file/d/1LdxcPgcJ50FSOPbEg61B6fH7mjzlYndV/preview",
        to: "/text/giaiphaunguoi",
    },
];

export { giaiPhauNguoi };
